#!/bin/bash

## Files and cmd
FILE="/home/luffy/.cache/eww_launch.dashboard"
CFG="/home/luffy/.config/eww/dashboard"
EWW="/usr/local/bin/eww/eww"  # Replace with the full path to `eww`


## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} --config "$CFG" open-many \
		   background \
		   profile \
		   system \
		   clock \
		   uptime \
		   music \
		   github \
		   reddit \
		   twitter \
		   youtube \
		   weather \
		   apps \
		   mail \
		   logout \
		   sleep \
		   reboot \
		   poweroff \
		   folders
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	${EWW} --config "$CFG" close \
					background profile system clock uptime music github \
					reddit twitter youtube weather apps mail logout sleep reboot poweroff folders
	rm "$FILE"
fi
