#!/bin/bash

## Open folders in nemo
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW="/usr/local/bin/eww/eww"

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system clock uptime music github \
					reddit twitter youtube weather apps mail logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--dl" ]]; then
	close_dash && nemo ~/Downloads &

elif [[ "$1" == "--docs" ]]; then
	close_dash && nemo ~/Documents &

elif [[ "$1" == "--music" ]]; then
	close_dash && nemo ~/Music &

elif [[ "$1" == "--pics" ]]; then
	close_dash && nemo ~/Pictures &

elif [[ "$1" == "--cfg" ]]; then
	close_dash && nemo ~/.config &

elif [[ "$1" == "--local" ]]; then
	close_dash && nemo ~/.local/share &

fi
